### ISSUE TITLE
Noob here

### ISSUE THREAD

**Issue by dackdel** [GoogleChrome/guitar-tuner#11]
How do I set this up on my localhost? Could you guide me like a html/css/js noob.

**Comment by arturparkhisenko** [comment]
@dackdel you need install nodejs + npm and when you have downloaded project, you must run `npm i` and this will install all dependencies for project, after that you can use a gulp tasks from [that](https://github.com/GoogleChrome/guitar-tuner/blob/master/gulpfile.js) file.

**Comment by alessiob** [comment]
Sorry, I'm also a newbie with all the involved tools. I installed npm and other stuff, ran `npm i` and then `gulp`. Unfortunately, the import line `import ToasterInstance from './libs/Toaster';` in "scripts/guitartuner-core.js" is not replaced/processed. Hence, the "vulcanized" html file in the dist directory (namely, dist/index.html) fails and the only thing I can see in the browser is the version number. It would be great if a few lines could be added to the main README file. A short description and a list of references about how to "compile" would help a lot.

**Comment by planetalk** [comment]
I would also like to know exactly how to set this up so I can use it on my site. Thanks.

**Comment by paullewis** [comment]
Thanks for the question. Sorry for the delay. I added a bunch of instructions:

https://github.com/GoogleChrome/guitar-tuner/blob/master/README.md#running-the-site-locally
