### ISSUE TITLE
Change A# to Bb

### ISSUE THREAD

**Issue by grayghostvisuals** [GoogleChrome/guitar-tuner#2]
I'm a snob I know. Change the A# to Bb. Tuner is great.

**Comment by grayghostvisuals** [comment]
I have this forked and happy to fix when ur ready to say it's ok (which you will) :8ball:

**Comment by paullewis** [comment]
Hahaha! Thanks for being willing to do a PR. I want to confirm it's definitely wrong first, though.

**Comment by grayghostvisuals** [comment]
@paullewis :+1:

**Comment by paullewis** [comment]
Mrs. Lewis reckons convention matches your suggestion. On the other side, according to my mum (a music teacher) it's not _incorrect_ to have A#, just less common, but I'm nothing if not conventional sooooo fixed.

**Comment by grayghostvisuals** [comment]
@paullewis Always listen to the wife and mum I always say. Thank you for putting up with my torture and giving me a great example to study.

**Comment by lukeed** [comment]
+1 for the lol
